### ISSUE TITLE
MIDAS calendar emails are coming in strange.

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#120]
Emails come in like this
<img width="1365" alt="Screenshot 2024-02-06 at 5 46 57 PM" src="https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/56dee8d6-0906-42af-9152-5b402dae8c17">

Ticket was created like this

<img width="1156" alt="Screenshot 2024-02-06 at 5 49 46 PM" src="https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/67d8c900-eabc-4184-9758-e40546259bdd">

**Comment by braxtonan** [comment]
Issue has been resolved with new email parsing I believe
