### ISSUE TITLE
WO linking not working for archived tickets.

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#135]
Question about the new help desk. I am trying to migrate ticket 110230 over. I have created the new ticket [help.provo.edu/controllers/tickets/edit_ticket.php?id=125032](http://help.provo.edu/controllers/tickets/edit_ticket.php?id=125032), but when I type WO#A-110230 it does not like to the archived ticket. Do I need to use a different format for that link?

**Comment by joshespi** [comment]
tested in https://help.provo.edu/controllers/tickets/edit_ticket.php?id=125032

made a note with WO#110230 which does work

**Comment by braxtonan** [comment]
Resolved issue in stage, creating PR
