### ISSUE TITLE
Suggestion: Is there anyway we can add a "latest notes" collum under My Assigned Tickets like in the old system?

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#146]
Suggestion: Is there anyway we can add a "latest notes" collum under My Assigned Tickets like in the old system? This, at least for me, makes it easier to see what I've done at a glance instead of having to go into the ticket to see where I am with it.
Especially when I have multiple repair tickets, inactive student tickets, etc.

This is the column I believe Shelby is requesting
![Screenshot 2024-02-08 at 8 41 20 AM](https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/6da21d05-5176-4ba2-91b0-271ffc151602)

**Comment by braxtonan** [comment]
Implemented feature, created PR https://github.com/Provo-City-School-District/help.provo.edu/pull/156

**Comment by braxtonan** [comment]
Closing issue
