### ISSUE TITLE
merging not resolving old ticket

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#157]
Emma Said

When 

> I am merging tickets to get rid of duplicates, it is not closing out the others. Can that be looked at please?

**Comment by joshespi** [comment]
Megan Redford
  [12:59 PM](https://psdtech.slack.com/archives/C06HMF3B448/p1707422364897839)
I had a ticket (#70) that created two duplicate tickets (72 and 74). Is that a user issue or the system?

Emma Hurst
  [8 minutes ago](https://psdtech.slack.com/archives/C06HMF3B448/p1707422416898709?thread_ts=1707422364.897839&cid=C06HMF3B448)
I think a system. I resolved two of them. I was trying to merge and it was not working

**Comment by braxtonan** [comment]
Fixed this and pushed to stage. It marks a ticket as closed if it is merged into another ticket

**Comment by braxtonan** [comment]
Marking issue as closed, changes are live
