### ISSUE TITLE
Also when a client updates the WO it has a ton of other information inside of the update which makes it a little confusing ...

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#162]
Also when a client updates the WO it has a ton of other information inside of the update which makes it a little confusing ...
![Screenshot 2024-02-08 at 11 44 44 AM](https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/d824c773-5ccc-4d01-8e73-b0f7a0841440)

**Comment by braxtonan** [comment]
Marking as resolved - email parsing has been cleaned up a lot and more or less matches the trailing garbage that existed on the previous system
