### ISSUE TITLE
When I put in a hidden note it is invisible to me as well, I can just see it in the ticket history.

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#169]
When I put in a hidden note it is invisible to me as well, I can just see it in the ticket history.

**Comment by braxtonan** [comment]
Looked at code and found that the permissions checks for is_admin. It should check for is_tech. Made the change and created a PR.

**Comment by braxtonan** [comment]
This issue also needs to hide the ticket logs so I will reopen this

**Comment by joshespi** [comment]
this is finished. clients cant see history
