### ISSUE TITLE
Due Date Alerts Too Aggressive (Bug?)

### ISSUE THREAD

**Issue by braxtonan** [Provo-City-School-District/help.provo.edu#173]
Heard from Gene that the due dates seem to be a bit aggressive, as it was warning him for a 48 hour update on a ticket he recently put in

**Comment by joshespi** [comment]
I'll investigate the 48 hour alerts.

I fixed this morning the due date alerts since it wasn't actually taking into account exclude or weekends.

**Comment by joshespi** [comment]
I believe I found the issue. timezone on the mariadb server as default(UTC).  thus when a new note would get entered and update the "last updated" column it would be 6 hours in the future thus only getting 42 hours before 48 hour alert would fire.

its also possible that the future date might have caused additional issues with the way the alert time was calculated. 

applied changes to mariadb dockerfile here https://github.com/Provo-City-School-District/help.provo.edu/commit/421dd00d944bbc529df42084429e582efe531650

does require rebuilding docker container.

**Comment by joshespi** [comment]
fix deployed
