### ISSUE TITLE
Search Labels Change suggestion

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#175]
<img width="956" alt="Screenshot 2024-02-09 at 11 38 01 AM" src="https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/1681a09f-8541-4a4b-8843-12089561d9e4">

**Comment by braxtonan** [comment]
Merged this into stage, as well as sorting the techs alphabetically

**Comment by joshespi** [comment]
this should have closed. already pushed live
