### ISSUE TITLE
Clients can read and send notes/tickets through entirely email

### ISSUE THREAD

**Issue by BrightonCProvo** [Provo-City-School-District/help.provo.edu#2]
Similar to the way the Solarwinds helpdesk works now where users can respond to the email to add notes to a ticket

**Comment by joshespi** [comment]
Create ticket works

add note works

a few other situations we need to address is if a client responds to a ticket how that is handled.

we probably need to send some sort of receipt email to the client announcing the opening of the ticket so they know it happened. We can probably re-use that for when they create tickets normally.

**Comment by joshespi** [comment]
created separate issues for the ticket creation receipt, and for the reply to ticket issue.
