### ISSUE TITLE
Verify File Uploads

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#39]
Verify File type

Limit Types that can be uploaded

Check file size to verify not too big.

if image, compress and size to 1500px wide with no cropping

**Comment by braxtonan** [comment]
Validated file content type using MIME and checked file size before moving to server (can also do a client side check too to prevent confusion in the future). 

Currently 50MiB max upload size. Needs to be increased to 100MiB soon but requires max POST length to be changed.

Commit 652a0a68d5bc959ece3bfb327a294021492206b4

**Comment by joshespi** [comment]
this looks to be complete.
