### ISSUE TITLE
Intern Role

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#394]

**Comment by braxtonan** [comment]
Started work on this. The route I decided to take was to make tickets 'intern visible' by adding a checkbox to edit_ticket.php. Users with is_intern = 1 (on users table) can now log in and will see Intern tickets and can work on those.

**Comment by joshespi** [comment]
going to get some eyes on this from the people that will be managing the intern for any additional features or changes.

**Comment by braxtonan** [comment]
I heard from Josh that the people managing interns like the changes as they are. Marking issue as complete.
