### ISSUE TITLE
Learning for faster backend

### ISSUE THREAD

**Issue by BrightonCProvo** [Provo-City-School-District/help.provo.edu#41]
# Yew
Yew does say that, Yew is not 1.0 yet. Be prepared to do major refactoring due to breaking API changes.
However, many people have also been saying that migration is very easy, we'll want to talk about this.

Github:
https://github.com/yewstack/yew

Definitely still in strong development, with over 300 contributors.
Not worried about stability, and very slight worries about rewrites before 1.0, however, it is stable currently, just before 1.0 because of possible breaking API changes.

# Rust resources
The Book: https://doc.rust-lang.org/book/

A really great article about building an entire app with just rust: https://robert.kra.hn/posts/2022-04-03_rust-web-wasm/

# Options
Ok, so now that you have some resources, we need to think about how we want to do this.
No matter what, we'd have to use Reqwest: https://docs.rs/reqwest/latest/reqwest/
That's not much of a worry though because I already know it, and have used it with production level code.

Frontend would be Yew 

Backend could be PHP, Axum, Or Rocket

Auxm: https://github.com/tokio-rs/axum
Rocket: https://rocket.rs/

Also, if we wanted, we could use PHP for some things, and Auxm or Rocket for others. (We'd want to choose between Auxm and Rocket though)

# Best Choices
Performance wise, axum or rocket are our best choices, however ease of implementation would probably be PHP, depending on how quickly you pick up Rust, as it would be very fast for you to work on, and I'm good enough at it to be comfortable.

Between Axum and Rocket, I prefer Rocket, but you should look at both to see which you prefer.
Also, while we were talking, I realized I messed up. Yew would not remotely replace PHP as it is backend only. Yew would replace much of the js that we are currently using, and Rocket/Axum would end up replacing the PHP.

Rocket being my personal choice because creation is much faster, but Axum is more low level, so more options (kinda)

I will be learning Rocket and Yew for my personal project, so that would work, however, if you prefer PHP or Axum I am perfectly up for that.

Examples of what Yew can do: https://jetli.github.io/rust-yew-realworld-example-app/#/
That example's github: https://github.com/jetli/rust-yew-realworld-example-app

**Comment by joshespi** [comment]
should be fine to close
