### ISSUE TITLE
Dark Mode System Issue.

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#55]
Dark mode switches how it handles colors depending on system settings

website in dark mode for both screenshots

System in Dark mode
![Screenshot 2023-11-06 at 7 54 45 AM](https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/0992d6f4-d760-4ac6-b366-a7a33ae8a078)
System in Light Mode
![Screenshot 2023-11-06 at 7 54 38 AM](https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/2cdebdc7-b33d-4af6-8c33-d6e07b2f60a4)

**Comment by braxtonan** [comment]
Issue has been resolved
