### ISSUE TITLE
emailed ticket updates are not clearing update alerts

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#60]
emailed ticket updates are not clearing update alerts. should be as simple fix. we should have it also update the ticket updated time.

**Comment by joshespi** [comment]
we will want to make sure that client email updates DO NOT clear the 48 hour update alert since that is for the tech, but we do want to still have it update the "last update" time so that we can re-use that similarly for "waiting for client" status.

tech email updates SHOULD clear alerts and update "last update" time.

**Comment by joshespi** [comment]
it looks like these email updates are not updating the status back to open if its set to "waiting for client"

**Comment by braxtonan** [comment]
set ticket to go back to the open state unconditionally if a reply is received for it
