### ISSUE TITLE
attachments in email

### ISSUE THREAD

**Issue by joshespi** [Provo-City-School-District/help.provo.edu#71]
make sure attachments get attached to the ticket

**Comment by joshespi** [comment]
did a test this morning just to see what happens. I didn't see anything in the code to handle the attachments so it was as expected.

![Screenshot 2024-02-01 at 7 58 27 AM](https://github.com/Provo-City-School-District/help.provo.edu/assets/8398378/c8cd20fa-2ac7-4773-885e-7aaa037655c9)

**Comment by joshespi** [comment]
got really close, was having issues with the actual file not getting uploaded.

saved my changes locally but had to stop working on this issue so to not conflict with other developer changes.

will be implementing a branching workflow soon after we finish current push to get ready for launch to remedy the issue of modifying the same files.

**Comment by joshespi** [comment]
last error we are running into is our uploads folder is not getting proper permissions on container creation.

if we manually change the permission things work, but get overwritten as soon as the container is rebuilt.

**Comment by braxtonan** [comment]
Got attachments working from email, but like Josh said we are having some problems with docker. Going to wait until that is resolved and then we can close this issue.

**Comment by joshespi** [comment]
permissions issue resolved. tested both email uploading and regular ticket uploading and both are working on a fresh build
